# STATES MEAN
POST http://localhost:5000/api/states_mean HTTP/1.1
content-type: application/json

{
    "question": "Percent of adults aged 18 years and older who have an overweight classification"
}
###

# STATE MEAN
POST http://localhost:5000/api/state_mean HTTP/1.1
content-type: application/json

{
    "question": "Percent of adults aged 18 years and older who have an overweight classification",
    "state": "Alabama"
}
###

# GET RESULT ID 1
GET http://localhost:5000/api/get_results/1 HTTP/1.1
content-type: application/json
###


# GET RESULT ID 10
GET http://localhost:5000/api/get_results/10 HTTP/1.1
content-type: application/json
###

GET http://localhost:5000/api/num_jobs HTTP/1.1
content-type: application/json
###

GET http://localhost:5000/api/jobs HTTP/1.1
content-type: application/json
###

GET http://localhost:5000/api/results HTTP/1.1
content-type: application/json
###

