# INPUT 1
POST http://localhost:5000/api/best5 HTTP/1.1
content-type: application/json

{
    "question": "Percent of adults aged 18 years and older who have an overweight classification"
}
###

# INPUT 2
POST http://localhost:5000/api/best5 HTTP/1.1
content-type: application/json

{
    "question": "Percent of adults aged 18 years and older who have obesity"
}
###

GET http://localhost:5000/api/get_results/1 HTTP/1.1
content-type: application/json
###

GET http://localhost:5000/api/get_results/2 HTTP/1.1
content-type: application/json
###