POST http://localhost:5000/api/global_mean HTTP/1.1
content-type: application/json

{
    "question": "Percent of adults aged 18 years and older who have an overweight classification"
}
###

POST http://localhost:5000/api/global_mean HTTP/1.1
content-type: application/json

{
    "question": "Percent of adults aged 18 years and older who have obesity"
}
###

GET http://localhost:5000/api/get_results/2 HTTP/1.1
content-type: application/json
###